Repository oVirt/ovirt-site, pull requests merged in 2022-05, with the labels that each got.

#2881 4.5.0: add ovirt-engine-4.5.0.6 notes
  source/release/4.5.0/index.md
Labels: upstream

#2883 oVirt 4.5 docs - add tech preview notes
  source/documentation/common/install/proc-Installing_Red_Hat_Enterprise_Linux_Hosts.adoc
  source/documentation/common/prereqs/asm-Host_Requirements.adoc
  source/documentation/common/prereqs/ref-Host_CPU_Requirements.adoc
  source/download/alternate_downloads.md
  source/download/index.md
Labels: upstream

#2884 community: point to github
  source/community/index.md
Labels: upstream

#2880 community: monitoring CVEs
  source/community/index.md
Labels: upstream

#2851 BZ#2069972 Add Compatibility Level 4.7 to Release Notes table
  source/documentation/common/upgrade/compatibility_levels.adoc
Labels: infra

#2566 Add Synology DSM settings to NFS Server section
  source/develop/troubleshooting-nfs-storage-issues.md
Labels: upstream

#2903 rhel: updated instructions
  source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc
  source/documentation/common/upgrade/proc-Manually_Updating_Hosts.adoc
  source/documentation/common/upgrade/proc-Updating_Individual_Hosts.adoc
  source/documentation/common/upgrade/proc-Upgrading_hosts_to_4-5.adoc
  source/documentation/common/upgrade/proc-Upgrading_the_Manager_to_4-5.adoc
  source/download/alternate_downloads.md
  source/download/index.md
  source/download/install_on_rhel.md
  source/download/rpms_and_gpg.md
  source/release/4.5.0/index.md
Labels: upstream

#2905 Install on RHEL 9 instructions
  source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc
  source/documentation/common/upgrade/proc-Manually_Updating_Hosts.adoc
  source/documentation/common/upgrade/proc-Updating_Individual_Hosts.adoc
  source/documentation/common/upgrade/proc-Upgrading_hosts_to_4-5.adoc
  source/documentation/common/upgrade/proc-Upgrading_the_Manager_to_4-5.adoc
  source/download/alternate_downloads.md
  source/download/index.md
  source/download/install_on_rhel.md
  source/download/rpms_and_gpg.md
Labels: upstream

#2910 add rocky workaround
  source/download/install_on_rhel.md
Labels: upstream

#2914 bundle update
  Gemfile.lock
Labels: dependencies, ruby

#2931 Fix SNMP 3 feature page
  source/develop/release-management/features/infra/engine-snmp3.md
Labels: developer_guide, upstream
