Repository oVirt/ovirt-site, pull requests merged in 2022-04, with the labels that each got.

#2835 4.5 now requires mod_auth_openidc:2.3
  source/develop/developer-guide/migrating_to_github.md
  source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc
Labels: upstream

#2856 Fix typo ivp4 -> ipv4
  source/documentation/common/install/con-Recommended_practices_for_configuring_host_networks.adoc
Labels: content

#2843 oVirt 4.5.0 Release
  htmlproofer_test.rb
  source/community/get-involved/repository-mirrors.md
  source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc
  source/documentation/common/install/proc-Installing_Red_Hat_Virtualization_Hosts.adoc
  source/documentation/common/install/proc_installing-a-third-party-package-on-ovirt-node.adoc
  source/documentation/common/install/snip-Enable_virt_module.adoc
  source/documentation/common/storage/ref-Preparing_Red_Hat_Gluster_Storage.adoc
  source/documentation/common/upgrade/proc-Manually_Updating_Hosts.adoc
  source/documentation/common/upgrade/proc-Updating_Individual_Hosts.adoc
  source/documentation/common/upgrade/proc-Updating_the_Red_Hat_Virtualization_Manager.adoc
  source/documentation/common/upgrade/proc-Upgrading_hosts_to_4-5.adoc
  source/documentation/common/upgrade/proc-Upgrading_the_Manager_to_4-5.adoc
  source/documentation/common/upgrade/snip-RHV_upgrade_prerequisites.adoc
  source/documentation/index.haml
  source/documentation/upgrade_guide/assembly-Remote_Upgrading_from_4-4.adoc
  source/documentation/upgrade_guide/assembly-SHE_Upgrading_from_4-4.adoc
  source/documentation/upgrade_guide/assembly-Upgrading_from_4-4.adoc
  source/documentation/upgrade_guide/chap-Updates_between_Minor_Releases.adoc
  source/documentation/upgrade_guide/index.adoc
  source/documentation/virtual_machine_management_guide/topics/Installing_the_Guest_Agents_and_Drivers_on_Red_Hat_Enterprise_Linux.adoc
  source/download/alternate_downloads.md
  source/download/index.md
  source/download/install_on_rhel.md
  source/download/rpms_and_gpg.md
  source/images/banners/ovirt-4.5-GA.png
  source/index.haml
  source/release/4.5.0/index.md
Labels: documentation, content, in progress, upstream

#2865 Add download link for 4.5 stable release
  source/download/node.md
Labels: upstream

#2868 mark sso as deprecated
  source/develop/release-management/features/infra/sso.md
Labels: upstream

#2872 4.5.0: add engine 4.5.0.5 notes
  source/release/4.5.0/index.md
Labels: upstream

#2855 BZ2052963 - added systemtap to the table of removed features
  source/documentation/doc-Release_Notes/topics/ref-Removed_Features_RHV.adoc
Labels: integration
