Repository oVirt/ovirt-site, pull requests merged in 2022-03, with the labels that each got.

#2760 4.5: prepare for alpha release
  source/documentation/index.haml
  source/release/4.5.0/index.md
Labels: upstream

#2763 add 4.5 instructions
  source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc
  source/documentation/common/install/proc_installing-a-third-party-package-on-ovirt-node.adoc
  source/download/alternate_downloads.md
  source/download/index.md
  source/download/rpms_and_gpg.md
Labels: upstream

#2488 Add /community/users-list
  source/community/about/mailing-lists.md
  source/community/index.md
  source/community/users-list.md
Labels: upstream

#2788 fix oVirt Node master link
  source/download/node.md
Labels: upstream

#2787 Add oVirt Node 4.5-pre section
  source/download/node.md
Labels: upstream

#2801 drop Xen hosts support draft
  source/develop/devdocs.md
  source/develop/xen.md
Labels: upstream

#2805 Update QA page
  source/develop/qa/index.md
Labels: upstream

#2824 bundle update
  Gemfile.lock
Labels: dependencies

#2825 config: avoid to generate a few unneeded pages
  _config.yml
Labels: content
